//1. Import Area
// 'use client'
import "bootstrap/dist/css/bootstrap.min.css";
import './globals.css'
import { Inter } from 'next/font/google'

// Import {someNamedImpor} from 'somelibrary'

import Footer from "@/components/layouts/Footer";
import LeftAside from "@/components/layouts/LeftAside";
import RightAside from "@/components/layouts/RightAside";
import Header from "@/components/layouts/header";

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) { // function start
     
    // bootstrap js Imported here
    
    // function return statement
    return (
      <html lang="en">
        <body className={inter.className}>
        <div className="container-fluid">
          <Header />
              <main>
                <div className="row">
                  <LeftAside />
            {children}
            <RightAside />
                </div>
              </main>
              <Footer />
          </div>

        </body>
      </html>
    )


} // function closed
