//1. Import Area
// 'use client'
import "bootstrap/dist/css/bootstrap.min.css"
import './globals.css'
import { Inter } from 'next/font/google'

// Import {someNamedImpor} from 'somelibrary'
import Header from "@/components/Header";
import LeftAside from "@/components/LeftAside";
import RightAside from "@/components/RightAside";


const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({children}) { // function start
     
    // bootstrap js Imported here
    
    // function return statement
    return (
      <html lang="en">
        <body className={inter.className}>
          <div className="container-fluid">
          <Header />
          <main className="row">
            <LeftAside />
            {children}
            <RightAside />
          </main>
          <footer>Resize the browser window to see how the content respond to the resizing.</footer>
         </div>
        </body>
      </html>
    )


} // function closed
